[phases.setup]
nixPkgs = ["php", "php81Extensions.pdo", "php81Extensions.pdo_mysql"]

[start]
cmd = "php -S 0.0.0.0:8080"

[variables]
PORT = "8080"

# For Laravel applications
[phases.build]
cmds = ["composer install --no-dev"]

# If you need specific PHP extensions or packages
[phases.install]
cmds = ["composer install"]

# Optional: Configure Nginx if you're using it
[nginx]
docroot = "public"
