name: Deploy thing to Cloudways

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Cloudways via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.CLOUDWAYS_HOST }}
        username: ${{ secrets.CLOUDWAYS_USERNAME }}
        password: ${{ secrets.CLOUDWAYS_PASSWORD }}
        port: 22
        script: |
          cd /public_html/wp-content/themes/your-theme-name
          git pull origin main
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
