name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync to Cloudways (rsync over SSH)
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -az --delete --exclude='.git*' --exclude='.github/'
          path: ./                      # local source (the repo)
          remote_path: ~/public_html/   # Cloudways app path
          remote_host: ${{ secrets.CLOUDWAYS_HOST }}   # server IP
          remote_user: ${{ secrets.CLOUDWAYS_USER }}   # Application user
          remote_key:  ${{ secrets.CLOUDWAYS_SSH_KEY }}# private key