name: Deploy to Cloudways (SSH rsync)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CLOUDWAYS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Optional: strict host key checking off for CI
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: rsync to Cloudways
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -az --delete --exclude='.git*' --exclude='.github/' --exclude='node_modules/' --exclude='*.md' --exclude='LICENSE'
          path: ./
          remote_path: public_html/
          remote_host: ${{ secrets.CLOUDWAYS_HOST }}
          remote_user: ${{ secrets.CLOUDWAYS_USERNAME }}
          remote_port: 22